name: CentOS Mirror Switcher Test

on:
    push:
        branches: ["dev"]
    pull_request:
        branches: ["dev"]
    workflow_dispatch:

jobs:
    test-script:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                # 定义版本和架构组合
                os: [5, 6, 7, 8, 9]
                arch: [x86_64, arm64]
                # fail-fast 应该在 strategy 下
                exclude:
                    - os: 5
                      arch: arm64
                    - os: 6
                      arch: arm64
                    - os: 9
                      arch: arm64
            fail-fast: false
        steps:
            # 检出仓库
            - uses: actions/checkout@v4

            # 设置 QEMU 以支持 ARM 架构容器
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            # 设置 Docker Buildx，以支持跨架构运行
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            # 运行测试
            - name: Run centos-mirror-switcher.sh
              run: |
                  # 生成 CentOS 镜像标签
                    if [ "${{ matrix.os }}" == "9" ]; then
                      IMAGE_TAG="quay.io/centos/centos:stream9"
                    else
                      IMAGE_TAG="centos:${{ matrix.os }}"
                    fi
                  # IMAGE_TAG="centos:${{ matrix.os }}"

                    if [ "${{ matrix.arch }}" == "arm64" ]; then
                      PLATFORM="linux/arm64"
                    else
                      PLATFORM="linux/amd64"
                    fi

                    echo "Testing $IMAGE_TAG on $PLATFORM"

                    docker run --rm --platform $PLATFORM \
                      -v $GITHUB_WORKSPACE:/workspace \
                      -w /workspace \
                      $IMAGE_TAG bash ./centos-mirror-switcher.sh
